/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.AddressBookType;
import com.coinbase.prime.model.DisplayUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;

public class AddressBookEntry {
    /**
     * UUID identifying this address book entry
     */
    @JsonProperty("id")
    private String id;

    /**
     * Currency symbol
     */
    @JsonProperty("currency_symbol")
    private String currencySymbol;

    /**
     * Name for this address book entry
     */
    @JsonProperty("name")
    private String name;

    /**
     * Cryptocurrency address
     */
    @JsonProperty("address")
    private String address;

    /**
     * Memo or destination tag for currencies which support them
     */
    @JsonProperty("account_identifier")
    private String accountIdentifier;

    /**
     * Name of the account identifier. For instance Destination Tag
     */
    @JsonProperty("account_identifier_name")
    private String accountIdentifierName;

    /**
     * State of this address book entry
     */
    @JsonProperty("state")
    private String state;

    /**
     * Link to a blockchain explorer
     */
    @JsonProperty("explorer_link")
    private String explorerLink;

    /**
     * When this entry was last used for a transaction
     */
    @JsonProperty("last_used_at")
    private OffsetDateTime lastUsedAt;

    /**
     * When this entry was added to the address book
     */
    @JsonProperty("added_at")
    private OffsetDateTime addedAt;

    @JsonProperty("added_by")
    private DisplayUser addedBy;

    @JsonProperty("type")
    private AddressBookType type;

    /**
     * counterparty id
     */
    @JsonProperty("counterparty_id")
    private String counterpartyId;

    public AddressBookEntry() {
    }

    public AddressBookEntry(Builder builder) {
        this.id = builder.id;
        this.currencySymbol = builder.currencySymbol;
        this.name = builder.name;
        this.address = builder.address;
        this.accountIdentifier = builder.accountIdentifier;
        this.accountIdentifierName = builder.accountIdentifierName;
        this.state = builder.state;
        this.explorerLink = builder.explorerLink;
        this.lastUsedAt = builder.lastUsedAt;
        this.addedAt = builder.addedAt;
        this.addedBy = builder.addedBy;
        this.type = builder.type;
        this.counterpartyId = builder.counterpartyId;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    public String getAccountIdentifier() {
        return accountIdentifier;
    }

    public void setAccountIdentifier(String accountIdentifier) {
        this.accountIdentifier = accountIdentifier;
    }
    public String getAccountIdentifierName() {
        return accountIdentifierName;
    }

    public void setAccountIdentifierName(String accountIdentifierName) {
        this.accountIdentifierName = accountIdentifierName;
    }
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
    public String getExplorerLink() {
        return explorerLink;
    }

    public void setExplorerLink(String explorerLink) {
        this.explorerLink = explorerLink;
    }
    public OffsetDateTime getLastUsedAt() {
        return lastUsedAt;
    }

    public void setLastUsedAt(OffsetDateTime lastUsedAt) {
        this.lastUsedAt = lastUsedAt;
    }
    public OffsetDateTime getAddedAt() {
        return addedAt;
    }

    public void setAddedAt(OffsetDateTime addedAt) {
        this.addedAt = addedAt;
    }
    public DisplayUser getAddedBy() {
        return addedBy;
    }

    public void setAddedBy(DisplayUser addedBy) {
        this.addedBy = addedBy;
    }
    public AddressBookType getType() {
        return type;
    }

    public void setType(AddressBookType type) {
        this.type = type;
    }
    public String getCounterpartyId() {
        return counterpartyId;
    }

    public void setCounterpartyId(String counterpartyId) {
        this.counterpartyId = counterpartyId;
    }
    public static class Builder {
        private String id;

        private String currencySymbol;

        private String name;

        private String address;

        private String accountIdentifier;

        private String accountIdentifierName;

        private String state;

        private String explorerLink;

        private OffsetDateTime lastUsedAt;

        private OffsetDateTime addedAt;

        private DisplayUser addedBy;

        private AddressBookType type;

        private String counterpartyId;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder currencySymbol(String currencySymbol) {
            this.currencySymbol = currencySymbol;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder address(String address) {
            this.address = address;
            return this;
        }

        public Builder accountIdentifier(String accountIdentifier) {
            this.accountIdentifier = accountIdentifier;
            return this;
        }

        public Builder accountIdentifierName(String accountIdentifierName) {
            this.accountIdentifierName = accountIdentifierName;
            return this;
        }

        public Builder state(String state) {
            this.state = state;
            return this;
        }

        public Builder explorerLink(String explorerLink) {
            this.explorerLink = explorerLink;
            return this;
        }

        public Builder lastUsedAt(OffsetDateTime lastUsedAt) {
            this.lastUsedAt = lastUsedAt;
            return this;
        }

        public Builder addedAt(OffsetDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        public Builder addedBy(DisplayUser addedBy) {
            this.addedBy = addedBy;
            return this;
        }

        public Builder type(AddressBookType type) {
            this.type = type;
            return this;
        }

        public Builder counterpartyId(String counterpartyId) {
            this.counterpartyId = counterpartyId;
            return this;
        }

        public AddressBookEntry build() {
            return new AddressBookEntry(this);
        }
    }
}

