/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.AdvancedTransferState;
import com.coinbase.prime.model.enums.AdvancedTransferType;
import com.coinbase.prime.model.BlindMatchMetadata;
import com.coinbase.prime.model.FundMovement;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class AdvancedTransfer {
    @JsonProperty("id")
    private String id;

    @JsonProperty("type")
    private AdvancedTransferType type;

    @JsonProperty("state")
    private AdvancedTransferState state;

    @JsonProperty("fund_movements")
    private List<FundMovement> fundMovements;

    @JsonProperty("blind_match_metadata")
    private BlindMatchMetadata blindMatchMetadata;

    public AdvancedTransfer() {
    }

    public AdvancedTransfer(Builder builder) {
        this.id = builder.id;
        this.type = builder.type;
        this.state = builder.state;
        this.fundMovements = builder.fundMovements;
        this.blindMatchMetadata = builder.blindMatchMetadata;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public AdvancedTransferType getType() {
        return type;
    }

    public void setType(AdvancedTransferType type) {
        this.type = type;
    }
    public AdvancedTransferState getState() {
        return state;
    }

    public void setState(AdvancedTransferState state) {
        this.state = state;
    }
    public List<FundMovement> getFundMovements() {
        return fundMovements;
    }

    public void setFundMovements(List<FundMovement> fundMovements) {
        this.fundMovements = fundMovements;
    }
    public BlindMatchMetadata getBlindMatchMetadata() {
        return blindMatchMetadata;
    }

    public void setBlindMatchMetadata(BlindMatchMetadata blindMatchMetadata) {
        this.blindMatchMetadata = blindMatchMetadata;
    }
    public static class Builder {
        private String id;

        private AdvancedTransferType type;

        private AdvancedTransferState state;

        private List<FundMovement> fundMovements;

        private BlindMatchMetadata blindMatchMetadata;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder type(AdvancedTransferType type) {
            this.type = type;
            return this;
        }

        public Builder state(AdvancedTransferState state) {
            this.state = state;
            return this;
        }

        public Builder fundMovements(List<FundMovement> fundMovements) {
            this.fundMovements = fundMovements;
            return this;
        }

        public Builder blindMatchMetadata(BlindMatchMetadata blindMatchMetadata) {
            this.blindMatchMetadata = blindMatchMetadata;
            return this;
        }

        public AdvancedTransfer build() {
            return new AdvancedTransfer(this);
        }
    }
}

