/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.XmControlStatus;
import com.coinbase.prime.model.enums.XmEntityCallStatus;
import com.coinbase.prime.model.XmLoan;
import com.coinbase.prime.model.XmMarginCall;
import com.coinbase.prime.model.enums.XmMarginLevel;
import com.coinbase.prime.model.XmSummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CrossMarginOverview {
    @JsonProperty("control_status")
    private XmControlStatus controlStatus;

    @JsonProperty("call_status")
    private XmEntityCallStatus callStatus;

    @JsonProperty("margin_level")
    private XmMarginLevel marginLevel;

    @JsonProperty("margin_summary")
    private XmSummary marginSummary;

    /**
     * List of active Xm margin calls
     */
    @JsonProperty("active_margin_calls")
    private List<XmMarginCall> activeMarginCalls;

    /**
     * List of active Xm loans
     */
    @JsonProperty("active_loans")
    private List<XmLoan> activeLoans;

    public CrossMarginOverview() {
    }

    public CrossMarginOverview(Builder builder) {
        this.controlStatus = builder.controlStatus;
        this.callStatus = builder.callStatus;
        this.marginLevel = builder.marginLevel;
        this.marginSummary = builder.marginSummary;
        this.activeMarginCalls = builder.activeMarginCalls;
        this.activeLoans = builder.activeLoans;
    }
    public XmControlStatus getControlStatus() {
        return controlStatus;
    }

    public void setControlStatus(XmControlStatus controlStatus) {
        this.controlStatus = controlStatus;
    }
    public XmEntityCallStatus getCallStatus() {
        return callStatus;
    }

    public void setCallStatus(XmEntityCallStatus callStatus) {
        this.callStatus = callStatus;
    }
    public XmMarginLevel getMarginLevel() {
        return marginLevel;
    }

    public void setMarginLevel(XmMarginLevel marginLevel) {
        this.marginLevel = marginLevel;
    }
    public XmSummary getMarginSummary() {
        return marginSummary;
    }

    public void setMarginSummary(XmSummary marginSummary) {
        this.marginSummary = marginSummary;
    }
    public List<XmMarginCall> getActiveMarginCalls() {
        return activeMarginCalls;
    }

    public void setActiveMarginCalls(List<XmMarginCall> activeMarginCalls) {
        this.activeMarginCalls = activeMarginCalls;
    }
    public List<XmLoan> getActiveLoans() {
        return activeLoans;
    }

    public void setActiveLoans(List<XmLoan> activeLoans) {
        this.activeLoans = activeLoans;
    }
    public static class Builder {
        private XmControlStatus controlStatus;

        private XmEntityCallStatus callStatus;

        private XmMarginLevel marginLevel;

        private XmSummary marginSummary;

        private List<XmMarginCall> activeMarginCalls;

        private List<XmLoan> activeLoans;

        public Builder controlStatus(XmControlStatus controlStatus) {
            this.controlStatus = controlStatus;
            return this;
        }

        public Builder callStatus(XmEntityCallStatus callStatus) {
            this.callStatus = callStatus;
            return this;
        }

        public Builder marginLevel(XmMarginLevel marginLevel) {
            this.marginLevel = marginLevel;
            return this;
        }

        public Builder marginSummary(XmSummary marginSummary) {
            this.marginSummary = marginSummary;
            return this;
        }

        public Builder activeMarginCalls(List<XmMarginCall> activeMarginCalls) {
            this.activeMarginCalls = activeMarginCalls;
            return this;
        }

        public Builder activeLoans(List<XmLoan> activeLoans) {
            this.activeLoans = activeLoans;
            return this;
        }

        public CrossMarginOverview build() {
            return new CrossMarginOverview(this);
        }
    }
}

