/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class DateOfBirth {
    private Long year;

    private Long month;

    private Long day;

    public DateOfBirth() {
    }

    public DateOfBirth(Builder builder) {
        this.year = builder.year;
        this.month = builder.month;
        this.day = builder.day;
    }
    public Long getYear() {
        return year;
    }

    public void setYear(Long year) {
        this.year = year;
    }
    public Long getMonth() {
        return month;
    }

    public void setMonth(Long month) {
        this.month = month;
    }
    public Long getDay() {
        return day;
    }

    public void setDay(Long day) {
        this.day = day;
    }
    public static class Builder {
        private Long year;

        private Long month;

        private Long day;

        public Builder year(Long year) {
            this.year = year;
            return this;
        }

        public Builder month(Long month) {
            this.month = month;
            return this;
        }

        public Builder day(Long day) {
            this.day = day;
            return this;
        }

        public DateOfBirth build() {
            return new DateOfBirth(this);
        }
    }
}

