/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class DefiBalance {
    @JsonProperty("network")
    private String network;

    @JsonProperty("protocol")
    private String protocol;

    @JsonProperty("net_usd_value")
    private String netUsdValue;

    public DefiBalance() {
    }

    public DefiBalance(Builder builder) {
        this.network = builder.network;
        this.protocol = builder.protocol;
        this.netUsdValue = builder.netUsdValue;
    }
    public String getNetwork() {
        return network;
    }

    public void setNetwork(String network) {
        this.network = network;
    }
    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }
    public String getNetUsdValue() {
        return netUsdValue;
    }

    public void setNetUsdValue(String netUsdValue) {
        this.netUsdValue = netUsdValue;
    }
    public static class Builder {
        private String network;

        private String protocol;

        private String netUsdValue;

        public Builder network(String network) {
            this.network = network;
            return this;
        }

        public Builder protocol(String protocol) {
            this.protocol = protocol;
            return this;
        }

        public Builder netUsdValue(String netUsdValue) {
            this.netUsdValue = netUsdValue;
            return this;
        }

        public DefiBalance build() {
            return new DefiBalance(this);
        }
    }
}

