/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.FcmScheduledMaintenance;
import com.coinbase.prime.model.enums.FcmTradingSessionClosedReason;
import com.coinbase.prime.model.enums.FcmTradingSessionState;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;

public class FcmTradingSessionDetails {
    /**
     * Whether the trading session is currently open
     */
    @JsonProperty("session_open")
    private boolean sessionOpen;

    /**
     * Trading session open time
     */
    @JsonProperty("open_time")
    private OffsetDateTime openTime;

    /**
     * Trading session close time
     */
    @JsonProperty("close_time")
    private OffsetDateTime closeTime;

    @JsonProperty("session_state")
    private FcmTradingSessionState sessionState;

    /**
     * Whether after-hours order entry is disabled
     */
    @JsonProperty("after_hours_order_entry_disabled")
    private boolean afterHoursOrderEntryDisabled;

    @JsonProperty("closed_reason")
    private FcmTradingSessionClosedReason closedReason;

    @JsonProperty("maintenance")
    private FcmScheduledMaintenance maintenance;

    /**
     * Settlement timestamp from previous trading day
     */
    @JsonProperty("settlement_timestamp")
    private OffsetDateTime settlementTimestamp;

    /**
     * Settlement price from previous trading day
     */
    @JsonProperty("settlement_price")
    private String settlementPrice;

    public FcmTradingSessionDetails() {
    }

    public FcmTradingSessionDetails(Builder builder) {
        this.sessionOpen = builder.sessionOpen;
        this.openTime = builder.openTime;
        this.closeTime = builder.closeTime;
        this.sessionState = builder.sessionState;
        this.afterHoursOrderEntryDisabled = builder.afterHoursOrderEntryDisabled;
        this.closedReason = builder.closedReason;
        this.maintenance = builder.maintenance;
        this.settlementTimestamp = builder.settlementTimestamp;
        this.settlementPrice = builder.settlementPrice;
    }
    public boolean getSessionOpen() {
        return sessionOpen;
    }

    public void setSessionOpen(boolean sessionOpen) {
        this.sessionOpen = sessionOpen;
    }
    public OffsetDateTime getOpenTime() {
        return openTime;
    }

    public void setOpenTime(OffsetDateTime openTime) {
        this.openTime = openTime;
    }
    public OffsetDateTime getCloseTime() {
        return closeTime;
    }

    public void setCloseTime(OffsetDateTime closeTime) {
        this.closeTime = closeTime;
    }
    public FcmTradingSessionState getSessionState() {
        return sessionState;
    }

    public void setSessionState(FcmTradingSessionState sessionState) {
        this.sessionState = sessionState;
    }
    public boolean getAfterHoursOrderEntryDisabled() {
        return afterHoursOrderEntryDisabled;
    }

    public void setAfterHoursOrderEntryDisabled(boolean afterHoursOrderEntryDisabled) {
        this.afterHoursOrderEntryDisabled = afterHoursOrderEntryDisabled;
    }
    public FcmTradingSessionClosedReason getClosedReason() {
        return closedReason;
    }

    public void setClosedReason(FcmTradingSessionClosedReason closedReason) {
        this.closedReason = closedReason;
    }
    public FcmScheduledMaintenance getMaintenance() {
        return maintenance;
    }

    public void setMaintenance(FcmScheduledMaintenance maintenance) {
        this.maintenance = maintenance;
    }
    public OffsetDateTime getSettlementTimestamp() {
        return settlementTimestamp;
    }

    public void setSettlementTimestamp(OffsetDateTime settlementTimestamp) {
        this.settlementTimestamp = settlementTimestamp;
    }
    public String getSettlementPrice() {
        return settlementPrice;
    }

    public void setSettlementPrice(String settlementPrice) {
        this.settlementPrice = settlementPrice;
    }
    public static class Builder {
        private boolean sessionOpen;

        private OffsetDateTime openTime;

        private OffsetDateTime closeTime;

        private FcmTradingSessionState sessionState;

        private boolean afterHoursOrderEntryDisabled;

        private FcmTradingSessionClosedReason closedReason;

        private FcmScheduledMaintenance maintenance;

        private OffsetDateTime settlementTimestamp;

        private String settlementPrice;

        public Builder sessionOpen(boolean sessionOpen) {
            this.sessionOpen = sessionOpen;
            return this;
        }

        public Builder openTime(OffsetDateTime openTime) {
            this.openTime = openTime;
            return this;
        }

        public Builder closeTime(OffsetDateTime closeTime) {
            this.closeTime = closeTime;
            return this;
        }

        public Builder sessionState(FcmTradingSessionState sessionState) {
            this.sessionState = sessionState;
            return this;
        }

        public Builder afterHoursOrderEntryDisabled(boolean afterHoursOrderEntryDisabled) {
            this.afterHoursOrderEntryDisabled = afterHoursOrderEntryDisabled;
            return this;
        }

        public Builder closedReason(FcmTradingSessionClosedReason closedReason) {
            this.closedReason = closedReason;
            return this;
        }

        public Builder maintenance(FcmScheduledMaintenance maintenance) {
            this.maintenance = maintenance;
            return this;
        }

        public Builder settlementTimestamp(OffsetDateTime settlementTimestamp) {
            this.settlementTimestamp = settlementTimestamp;
            return this;
        }

        public Builder settlementPrice(String settlementPrice) {
            this.settlementPrice = settlementPrice;
            return this;
        }

        public FcmTradingSessionDetails build() {
            return new FcmTradingSessionDetails(this);
        }
    }
}

