/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.TransferLocation;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class FundMovement {
    @JsonProperty("id")
    private String id;

    @JsonProperty("source")
    private TransferLocation source;

    @JsonProperty("target")
    private TransferLocation target;

    @JsonProperty("currency")
    private String currency;

    @JsonProperty("amount")
    private String amount;

    public FundMovement() {
    }

    public FundMovement(Builder builder) {
        this.id = builder.id;
        this.source = builder.source;
        this.target = builder.target;
        this.currency = builder.currency;
        this.amount = builder.amount;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public TransferLocation getSource() {
        return source;
    }

    public void setSource(TransferLocation source) {
        this.source = source;
    }
    public TransferLocation getTarget() {
        return target;
    }

    public void setTarget(TransferLocation target) {
        this.target = target;
    }
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }
    public static class Builder {
        private String id;

        private TransferLocation source;

        private TransferLocation target;

        private String currency;

        private String amount;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder source(TransferLocation source) {
            this.source = source;
            return this;
        }

        public Builder target(TransferLocation target) {
            this.target = target;
            return this;
        }

        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        public Builder amount(String amount) {
            this.amount = amount;
            return this;
        }

        public FundMovement build() {
            return new FundMovement(this);
        }
    }
}

