/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.ContractExpiryType;
import com.coinbase.prime.model.PerpetualProductDetails;
import com.coinbase.prime.model.enums.RiskManagementType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;

public class FutureProductDetails {
    /**
     * Contract code identifier
     */
    @JsonProperty("contract_code")
    private String contractCode;

    /**
     * Contract size
     */
    @JsonProperty("contract_size")
    private String contractSize;

    /**
     * Contract expiry timestamp
     */
    @JsonProperty("contract_expiry")
    private OffsetDateTime contractExpiry;

    /**
     * Contract root unit (underlying asset)
     */
    @JsonProperty("contract_root_unit")
    private String contractRootUnit;

    @JsonProperty("contract_expiry_type")
    private ContractExpiryType contractExpiryType;

    @JsonProperty("risk_managed_by")
    private RiskManagementType riskManagedBy;

    /**
     * The venue this product trades on
     */
    @JsonProperty("venue")
    private String venue;

    /**
     * Descriptive name for the product group
     */
    @JsonProperty("group_description")
    private String groupDescription;

    /**
     * IANA time zone for contract expiration
     */
    @JsonProperty("contract_expiry_timezone")
    private String contractExpiryTimezone;

    /**
     * Short version of the group description
     */
    @JsonProperty("group_short_description")
    private String groupShortDescription;

    @JsonProperty("perpetual_details")
    private PerpetualProductDetails perpetualDetails;

    public FutureProductDetails() {
    }

    public FutureProductDetails(Builder builder) {
        this.contractCode = builder.contractCode;
        this.contractSize = builder.contractSize;
        this.contractExpiry = builder.contractExpiry;
        this.contractRootUnit = builder.contractRootUnit;
        this.contractExpiryType = builder.contractExpiryType;
        this.riskManagedBy = builder.riskManagedBy;
        this.venue = builder.venue;
        this.groupDescription = builder.groupDescription;
        this.contractExpiryTimezone = builder.contractExpiryTimezone;
        this.groupShortDescription = builder.groupShortDescription;
        this.perpetualDetails = builder.perpetualDetails;
    }
    public String getContractCode() {
        return contractCode;
    }

    public void setContractCode(String contractCode) {
        this.contractCode = contractCode;
    }
    public String getContractSize() {
        return contractSize;
    }

    public void setContractSize(String contractSize) {
        this.contractSize = contractSize;
    }
    public OffsetDateTime getContractExpiry() {
        return contractExpiry;
    }

    public void setContractExpiry(OffsetDateTime contractExpiry) {
        this.contractExpiry = contractExpiry;
    }
    public String getContractRootUnit() {
        return contractRootUnit;
    }

    public void setContractRootUnit(String contractRootUnit) {
        this.contractRootUnit = contractRootUnit;
    }
    public ContractExpiryType getContractExpiryType() {
        return contractExpiryType;
    }

    public void setContractExpiryType(ContractExpiryType contractExpiryType) {
        this.contractExpiryType = contractExpiryType;
    }
    public RiskManagementType getRiskManagedBy() {
        return riskManagedBy;
    }

    public void setRiskManagedBy(RiskManagementType riskManagedBy) {
        this.riskManagedBy = riskManagedBy;
    }
    public String getVenue() {
        return venue;
    }

    public void setVenue(String venue) {
        this.venue = venue;
    }
    public String getGroupDescription() {
        return groupDescription;
    }

    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription;
    }
    public String getContractExpiryTimezone() {
        return contractExpiryTimezone;
    }

    public void setContractExpiryTimezone(String contractExpiryTimezone) {
        this.contractExpiryTimezone = contractExpiryTimezone;
    }
    public String getGroupShortDescription() {
        return groupShortDescription;
    }

    public void setGroupShortDescription(String groupShortDescription) {
        this.groupShortDescription = groupShortDescription;
    }
    public PerpetualProductDetails getPerpetualDetails() {
        return perpetualDetails;
    }

    public void setPerpetualDetails(PerpetualProductDetails perpetualDetails) {
        this.perpetualDetails = perpetualDetails;
    }
    public static class Builder {
        private String contractCode;

        private String contractSize;

        private OffsetDateTime contractExpiry;

        private String contractRootUnit;

        private ContractExpiryType contractExpiryType;

        private RiskManagementType riskManagedBy;

        private String venue;

        private String groupDescription;

        private String contractExpiryTimezone;

        private String groupShortDescription;

        private PerpetualProductDetails perpetualDetails;

        public Builder contractCode(String contractCode) {
            this.contractCode = contractCode;
            return this;
        }

        public Builder contractSize(String contractSize) {
            this.contractSize = contractSize;
            return this;
        }

        public Builder contractExpiry(OffsetDateTime contractExpiry) {
            this.contractExpiry = contractExpiry;
            return this;
        }

        public Builder contractRootUnit(String contractRootUnit) {
            this.contractRootUnit = contractRootUnit;
            return this;
        }

        public Builder contractExpiryType(ContractExpiryType contractExpiryType) {
            this.contractExpiryType = contractExpiryType;
            return this;
        }

        public Builder riskManagedBy(RiskManagementType riskManagedBy) {
            this.riskManagedBy = riskManagedBy;
            return this;
        }

        public Builder venue(String venue) {
            this.venue = venue;
            return this;
        }

        public Builder groupDescription(String groupDescription) {
            this.groupDescription = groupDescription;
            return this;
        }

        public Builder contractExpiryTimezone(String contractExpiryTimezone) {
            this.contractExpiryTimezone = contractExpiryTimezone;
            return this;
        }

        public Builder groupShortDescription(String groupShortDescription) {
            this.groupShortDescription = groupShortDescription;
            return this;
        }

        public Builder perpetualDetails(PerpetualProductDetails perpetualDetails) {
            this.perpetualDetails = perpetualDetails;
            return this;
        }

        public FutureProductDetails build() {
            return new FutureProductDetails(this);
        }
    }
}

