/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.SweepAmount;
import com.coinbase.prime.model.enums.FuturesSweepStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;

public class FuturesSweep {
    /**
     * Sweep ID
     */
    @JsonProperty("id")
    private String id;

    @JsonProperty("requested_amount")
    private SweepAmount requestedAmount;

    /**
     * Should sweep all
     */
    @JsonProperty("should_sweep_all")
    private Boolean shouldSweepAll;

    @JsonProperty("status")
    private FuturesSweepStatus status;

    /**
     * Scheduled time
     */
    @JsonProperty("scheduled_time")
    private OffsetDateTime scheduledTime;

    public FuturesSweep() {
    }

    public FuturesSweep(Builder builder) {
        this.id = builder.id;
        this.requestedAmount = builder.requestedAmount;
        this.shouldSweepAll = builder.shouldSweepAll;
        this.status = builder.status;
        this.scheduledTime = builder.scheduledTime;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public SweepAmount getRequestedAmount() {
        return requestedAmount;
    }

    public void setRequestedAmount(SweepAmount requestedAmount) {
        this.requestedAmount = requestedAmount;
    }
    public Boolean getShouldSweepAll() {
        return shouldSweepAll;
    }

    public void setShouldSweepAll(Boolean shouldSweepAll) {
        this.shouldSweepAll = shouldSweepAll;
    }
    public FuturesSweepStatus getStatus() {
        return status;
    }

    public void setStatus(FuturesSweepStatus status) {
        this.status = status;
    }
    public OffsetDateTime getScheduledTime() {
        return scheduledTime;
    }

    public void setScheduledTime(OffsetDateTime scheduledTime) {
        this.scheduledTime = scheduledTime;
    }
    public static class Builder {
        private String id;

        private SweepAmount requestedAmount;

        private Boolean shouldSweepAll;

        private FuturesSweepStatus status;

        private OffsetDateTime scheduledTime;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder requestedAmount(SweepAmount requestedAmount) {
            this.requestedAmount = requestedAmount;
            return this;
        }

        public Builder shouldSweepAll(Boolean shouldSweepAll) {
            this.shouldSweepAll = shouldSweepAll;
            return this;
        }

        public Builder status(FuturesSweepStatus status) {
            this.status = status;
            return this;
        }

        public Builder scheduledTime(OffsetDateTime scheduledTime) {
            this.scheduledTime = scheduledTime;
            return this;
        }

        public FuturesSweep build() {
            return new FuturesSweep(this);
        }
    }
}

