/*
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GoogleTypeDate {
    /**
     * Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.
     */
    @JsonProperty("year")
    private Integer year;

    /**
     * Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.
     */
    @JsonProperty("month")
    private Integer month;

    /**
     * Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn&#39;t significant.
     */
    @JsonProperty("day")
    private Integer day;

    public GoogleTypeDate() {
    }

    public GoogleTypeDate(Builder builder) {
        this.year = builder.year;
        this.month = builder.month;
        this.day = builder.day;
    }
    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }
    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }
    public static class Builder {
        private Integer year;

        private Integer month;

        private Integer day;

        public Builder year(Integer year) {
            this.year = year;
            return this;
        }

        public Builder month(Integer month) {
            this.month = month;
            return this;
        }

        public Builder day(Integer day) {
            this.day = day;
            return this;
        }

        public GoogleTypeDate build() {
            return new GoogleTypeDate(this);
        }
    }
}

