/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.MarginCallRecord;
import com.coinbase.prime.model.MarginSummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class MarginInformation {
    /**
     * The current margin call records
     */
    @JsonProperty("margin_call_records")
    private List<MarginCallRecord> marginCallRecords;

    @JsonProperty("margin_summary")
    private MarginSummary marginSummary;

    public MarginInformation() {
    }

    public MarginInformation(Builder builder) {
        this.marginCallRecords = builder.marginCallRecords;
        this.marginSummary = builder.marginSummary;
    }
    public List<MarginCallRecord> getMarginCallRecords() {
        return marginCallRecords;
    }

    public void setMarginCallRecords(List<MarginCallRecord> marginCallRecords) {
        this.marginCallRecords = marginCallRecords;
    }
    public MarginSummary getMarginSummary() {
        return marginSummary;
    }

    public void setMarginSummary(MarginSummary marginSummary) {
        this.marginSummary = marginSummary;
    }
    public static class Builder {
        private List<MarginCallRecord> marginCallRecords;

        private MarginSummary marginSummary;

        public Builder marginCallRecords(List<MarginCallRecord> marginCallRecords) {
            this.marginCallRecords = marginCallRecords;
            return this;
        }

        public Builder marginSummary(MarginSummary marginSummary) {
            this.marginSummary = marginSummary;
            return this;
        }

        public MarginInformation build() {
            return new MarginInformation(this);
        }
    }
}

