/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.Network;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class NetworkDetails {
    @JsonProperty("network")
    private Network network;

    /**
     * The name of the network
     */
    @JsonProperty("name")
    private String name;

    /**
     * The maximum number of decimals supported for this network
     */
    @JsonProperty("max_decimals")
    private String maxDecimals;

    /**
     * Indicates whether this network is the default network for the asset
     */
    @JsonProperty("default")
    private Boolean _default;

    /**
     * Indicates whether this network supports trading
     */
    @JsonProperty("trading_supported")
    private Boolean tradingSupported;

    /**
     * Indicates whether this network supports vault
     */
    @JsonProperty("vault_supported")
    private Boolean vaultSupported;

    /**
     * Indicates whether this network supports prime custody
     */
    @JsonProperty("prime_custody_supported")
    private Boolean primeCustodySupported;

    /**
     * Indicates whether this network requires a destination tag
     */
    @JsonProperty("destination_tag_required")
    private Boolean destinationTagRequired;

    /**
     * Base URL to our recommended block explorer (crypto only)
     */
    @JsonProperty("network_link")
    private String networkLink;

    /**
     * Indicates the symbol that can be used to query other endpoints, related to transactions, wallets, and activities, to get information particularly for this asset on the network
     */
    @JsonProperty("network_scoped_symbol")
    private String networkScopedSymbol;

    public NetworkDetails() {
    }

    public NetworkDetails(Builder builder) {
        this.network = builder.network;
        this.name = builder.name;
        this.maxDecimals = builder.maxDecimals;
        this._default = builder._default;
        this.tradingSupported = builder.tradingSupported;
        this.vaultSupported = builder.vaultSupported;
        this.primeCustodySupported = builder.primeCustodySupported;
        this.destinationTagRequired = builder.destinationTagRequired;
        this.networkLink = builder.networkLink;
        this.networkScopedSymbol = builder.networkScopedSymbol;
    }
    public Network getNetwork() {
        return network;
    }

    public void setNetwork(Network network) {
        this.network = network;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public String getMaxDecimals() {
        return maxDecimals;
    }

    public void setMaxDecimals(String maxDecimals) {
        this.maxDecimals = maxDecimals;
    }
    public Boolean getDefault() {
        return _default;
    }

    public void setDefault(Boolean _default) {
        this._default = _default;
    }
    public Boolean getTradingSupported() {
        return tradingSupported;
    }

    public void setTradingSupported(Boolean tradingSupported) {
        this.tradingSupported = tradingSupported;
    }
    public Boolean getVaultSupported() {
        return vaultSupported;
    }

    public void setVaultSupported(Boolean vaultSupported) {
        this.vaultSupported = vaultSupported;
    }
    public Boolean getPrimeCustodySupported() {
        return primeCustodySupported;
    }

    public void setPrimeCustodySupported(Boolean primeCustodySupported) {
        this.primeCustodySupported = primeCustodySupported;
    }
    public Boolean getDestinationTagRequired() {
        return destinationTagRequired;
    }

    public void setDestinationTagRequired(Boolean destinationTagRequired) {
        this.destinationTagRequired = destinationTagRequired;
    }
    public String getNetworkLink() {
        return networkLink;
    }

    public void setNetworkLink(String networkLink) {
        this.networkLink = networkLink;
    }
    public String getNetworkScopedSymbol() {
        return networkScopedSymbol;
    }

    public void setNetworkScopedSymbol(String networkScopedSymbol) {
        this.networkScopedSymbol = networkScopedSymbol;
    }
    public static class Builder {
        private Network network;

        private String name;

        private String maxDecimals;

        private Boolean _default;

        private Boolean tradingSupported;

        private Boolean vaultSupported;

        private Boolean primeCustodySupported;

        private Boolean destinationTagRequired;

        private String networkLink;

        private String networkScopedSymbol;

        public Builder network(Network network) {
            this.network = network;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder maxDecimals(String maxDecimals) {
            this.maxDecimals = maxDecimals;
            return this;
        }

        public Builder _default(Boolean _default) {
            this._default = _default;
            return this;
        }

        public Builder tradingSupported(Boolean tradingSupported) {
            this.tradingSupported = tradingSupported;
            return this;
        }

        public Builder vaultSupported(Boolean vaultSupported) {
            this.vaultSupported = vaultSupported;
            return this;
        }

        public Builder primeCustodySupported(Boolean primeCustodySupported) {
            this.primeCustodySupported = primeCustodySupported;
            return this;
        }

        public Builder destinationTagRequired(Boolean destinationTagRequired) {
            this.destinationTagRequired = destinationTagRequired;
            return this;
        }

        public Builder networkLink(String networkLink) {
            this.networkLink = networkLink;
            return this;
        }

        public Builder networkScopedSymbol(String networkScopedSymbol) {
            this.networkScopedSymbol = networkScopedSymbol;
            return this;
        }

        public NetworkDetails build() {
            return new NetworkDetails(this);
        }
    }
}

