/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;

public class PerpetualProductDetails {
    /**
     * Open interest
     */
    @JsonProperty("open_interest")
    private String openInterest;

    /**
     * Current funding rate
     */
    @JsonProperty("funding_rate")
    private String fundingRate;

    /**
     * Next funding time
     */
    @JsonProperty("funding_time")
    private OffsetDateTime fundingTime;

    /**
     * Maximum leverage allowed
     */
    @JsonProperty("max_leverage")
    private String maxLeverage;

    /**
     * The type of underlying for the perpetual product
     */
    @JsonProperty("underlying_type")
    private String underlyingType;

    public PerpetualProductDetails() {
    }

    public PerpetualProductDetails(Builder builder) {
        this.openInterest = builder.openInterest;
        this.fundingRate = builder.fundingRate;
        this.fundingTime = builder.fundingTime;
        this.maxLeverage = builder.maxLeverage;
        this.underlyingType = builder.underlyingType;
    }
    public String getOpenInterest() {
        return openInterest;
    }

    public void setOpenInterest(String openInterest) {
        this.openInterest = openInterest;
    }
    public String getFundingRate() {
        return fundingRate;
    }

    public void setFundingRate(String fundingRate) {
        this.fundingRate = fundingRate;
    }
    public OffsetDateTime getFundingTime() {
        return fundingTime;
    }

    public void setFundingTime(OffsetDateTime fundingTime) {
        this.fundingTime = fundingTime;
    }
    public String getMaxLeverage() {
        return maxLeverage;
    }

    public void setMaxLeverage(String maxLeverage) {
        this.maxLeverage = maxLeverage;
    }
    public String getUnderlyingType() {
        return underlyingType;
    }

    public void setUnderlyingType(String underlyingType) {
        this.underlyingType = underlyingType;
    }
    public static class Builder {
        private String openInterest;

        private String fundingRate;

        private OffsetDateTime fundingTime;

        private String maxLeverage;

        private String underlyingType;

        public Builder openInterest(String openInterest) {
            this.openInterest = openInterest;
            return this;
        }

        public Builder fundingRate(String fundingRate) {
            this.fundingRate = fundingRate;
            return this;
        }

        public Builder fundingTime(OffsetDateTime fundingTime) {
            this.fundingTime = fundingTime;
            return this;
        }

        public Builder maxLeverage(String maxLeverage) {
            this.maxLeverage = maxLeverage;
            return this;
        }

        public Builder underlyingType(String underlyingType) {
            this.underlyingType = underlyingType;
            return this;
        }

        public PerpetualProductDetails build() {
            return new PerpetualProductDetails(this);
        }
    }
}

