/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.PositionReferenceType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class PositionReference {
    /**
     * Reference ID
     */
    @JsonProperty("id")
    private String id;

    @JsonProperty("type")
    private PositionReferenceType type;

    public PositionReference() {
    }

    public PositionReference(Builder builder) {
        this.id = builder.id;
        this.type = builder.type;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public PositionReferenceType getType() {
        return type;
    }

    public void setType(PositionReferenceType type) {
        this.type = type;
    }
    public static class Builder {
        private String id;

        private PositionReferenceType type;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder type(PositionReferenceType type) {
            this.type = type;
            return this;
        }

        public PositionReference build() {
            return new PositionReference(this);
        }
    }
}

