/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.ProductPermissions;
import com.coinbase.prime.model.RFQProductDetails;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Product {
    /**
     * The product ID, written as &#x60;BASE-QUOTE&#x60;
     */
    @JsonProperty("id")
    private String id;

    /**
     * The smallest permitted unit of denomination for the base asset (varies by product)
     */
    @JsonProperty("base_increment")
    private String baseIncrement;

    /**
     * The smallest permitted unit of denomination for the quote asset (varies by product)
     */
    @JsonProperty("quote_increment")
    private String quoteIncrement;

    /**
     * The minimum size (in base asset units) for which an order can be placed
     */
    @JsonProperty("base_min_size")
    private String baseMinSize;

    /**
     * The minimum size (in quote asset units) for which an order can be placed
     */
    @JsonProperty("quote_min_size")
    private String quoteMinSize;

    /**
     * The maximum size (in base asset units) for which an order can be placed
     */
    @JsonProperty("base_max_size")
    private String baseMaxSize;

    /**
     * The maximum size (in quote asset units) for which an order can be placed
     */
    @JsonProperty("quote_max_size")
    private String quoteMaxSize;

    /**
     * Permissions given to the user for a product
     */
    @JsonProperty("permissions")
    private List<ProductPermissions> permissions;

    /**
     * The smallest permitted price increment for the product
     */
    @JsonProperty("price_increment")
    private String priceIncrement;

    @JsonProperty("rfq_product_details")
    private RFQProductDetails rfqProductDetails;

    public Product() {
    }

    public Product(Builder builder) {
        this.id = builder.id;
        this.baseIncrement = builder.baseIncrement;
        this.quoteIncrement = builder.quoteIncrement;
        this.baseMinSize = builder.baseMinSize;
        this.quoteMinSize = builder.quoteMinSize;
        this.baseMaxSize = builder.baseMaxSize;
        this.quoteMaxSize = builder.quoteMaxSize;
        this.permissions = builder.permissions;
        this.priceIncrement = builder.priceIncrement;
        this.rfqProductDetails = builder.rfqProductDetails;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public String getBaseIncrement() {
        return baseIncrement;
    }

    public void setBaseIncrement(String baseIncrement) {
        this.baseIncrement = baseIncrement;
    }
    public String getQuoteIncrement() {
        return quoteIncrement;
    }

    public void setQuoteIncrement(String quoteIncrement) {
        this.quoteIncrement = quoteIncrement;
    }
    public String getBaseMinSize() {
        return baseMinSize;
    }

    public void setBaseMinSize(String baseMinSize) {
        this.baseMinSize = baseMinSize;
    }
    public String getQuoteMinSize() {
        return quoteMinSize;
    }

    public void setQuoteMinSize(String quoteMinSize) {
        this.quoteMinSize = quoteMinSize;
    }
    public String getBaseMaxSize() {
        return baseMaxSize;
    }

    public void setBaseMaxSize(String baseMaxSize) {
        this.baseMaxSize = baseMaxSize;
    }
    public String getQuoteMaxSize() {
        return quoteMaxSize;
    }

    public void setQuoteMaxSize(String quoteMaxSize) {
        this.quoteMaxSize = quoteMaxSize;
    }
    public List<ProductPermissions> getPermissions() {
        return permissions;
    }

    public void setPermissions(List<ProductPermissions> permissions) {
        this.permissions = permissions;
    }
    public String getPriceIncrement() {
        return priceIncrement;
    }

    public void setPriceIncrement(String priceIncrement) {
        this.priceIncrement = priceIncrement;
    }
    public RFQProductDetails getRfqProductDetails() {
        return rfqProductDetails;
    }

    public void setRfqProductDetails(RFQProductDetails rfqProductDetails) {
        this.rfqProductDetails = rfqProductDetails;
    }
    public static class Builder {
        private String id;

        private String baseIncrement;

        private String quoteIncrement;

        private String baseMinSize;

        private String quoteMinSize;

        private String baseMaxSize;

        private String quoteMaxSize;

        private List<ProductPermissions> permissions;

        private String priceIncrement;

        private RFQProductDetails rfqProductDetails;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder baseIncrement(String baseIncrement) {
            this.baseIncrement = baseIncrement;
            return this;
        }

        public Builder quoteIncrement(String quoteIncrement) {
            this.quoteIncrement = quoteIncrement;
            return this;
        }

        public Builder baseMinSize(String baseMinSize) {
            this.baseMinSize = baseMinSize;
            return this;
        }

        public Builder quoteMinSize(String quoteMinSize) {
            this.quoteMinSize = quoteMinSize;
            return this;
        }

        public Builder baseMaxSize(String baseMaxSize) {
            this.baseMaxSize = baseMaxSize;
            return this;
        }

        public Builder quoteMaxSize(String quoteMaxSize) {
            this.quoteMaxSize = quoteMaxSize;
            return this;
        }

        public Builder permissions(List<ProductPermissions> permissions) {
            this.permissions = permissions;
            return this;
        }

        public Builder priceIncrement(String priceIncrement) {
            this.priceIncrement = priceIncrement;
            return this;
        }

        public Builder rfqProductDetails(RFQProductDetails rfqProductDetails) {
            this.rfqProductDetails = rfqProductDetails;
            return this;
        }

        public Product build() {
            return new Product(this);
        }
    }
}

