/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.TravelRuleParty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class RequestToSubmitTravelRuleDataForAnExistingDepositTransaction {
    @JsonProperty("originator")
    private TravelRuleParty originator;

    @JsonProperty("beneficiary")
    private TravelRuleParty beneficiary;

    @JsonProperty("is_self")
    private boolean isSelf;

    @JsonProperty("opt_out_of_ownership_verification")
    private boolean optOutOfOwnershipVerification;

    public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction() {
    }

    public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction(Builder builder) {
        this.originator = builder.originator;
        this.beneficiary = builder.beneficiary;
        this.isSelf = builder.isSelf;
        this.optOutOfOwnershipVerification = builder.optOutOfOwnershipVerification;
    }
    public TravelRuleParty getOriginator() {
        return originator;
    }

    public void setOriginator(TravelRuleParty originator) {
        this.originator = originator;
    }
    public TravelRuleParty getBeneficiary() {
        return beneficiary;
    }

    public void setBeneficiary(TravelRuleParty beneficiary) {
        this.beneficiary = beneficiary;
    }
    public boolean getIsSelf() {
        return isSelf;
    }

    public void setIsSelf(boolean isSelf) {
        this.isSelf = isSelf;
    }
    public boolean getOptOutOfOwnershipVerification() {
        return optOutOfOwnershipVerification;
    }

    public void setOptOutOfOwnershipVerification(boolean optOutOfOwnershipVerification) {
        this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
    }
    public static class Builder {
        private TravelRuleParty originator;

        private TravelRuleParty beneficiary;

        private boolean isSelf;

        private boolean optOutOfOwnershipVerification;

        public Builder originator(TravelRuleParty originator) {
            this.originator = originator;
            return this;
        }

        public Builder beneficiary(TravelRuleParty beneficiary) {
            this.beneficiary = beneficiary;
            return this;
        }

        public Builder isSelf(boolean isSelf) {
            this.isSelf = isSelf;
            return this;
        }

        public Builder optOutOfOwnershipVerification(boolean optOutOfOwnershipVerification) {
            this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
            return this;
        }

        public RequestToSubmitTravelRuleDataForAnExistingDepositTransaction build() {
            return new RequestToSubmitTravelRuleDataForAnExistingDepositTransaction(this);
        }
    }
}

