/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.enums.RewardSubtype;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class RewardMetadata {
    @JsonProperty("subtype")
    private RewardSubtype subtype;

    public RewardMetadata() {
    }

    public RewardMetadata(Builder builder) {
        this.subtype = builder.subtype;
    }
    public RewardSubtype getSubtype() {
        return subtype;
    }

    public void setSubtype(RewardSubtype subtype) {
        this.subtype = subtype;
    }
    public static class Builder {
        private RewardSubtype subtype;

        public Builder subtype(RewardSubtype subtype) {
            this.subtype = subtype;
            return this;
        }

        public RewardMetadata build() {
            return new RewardMetadata(this);
        }
    }
}

