/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class RiskAssessment {
    /**
     * Indicates if the transaction has been flagged for compliance concerns
     */
    private Boolean complianceRiskDetected;

    /**
     * Indicates if the transaction has been flagged for security concerns
     */
    private Boolean securityRiskDetected;

    public RiskAssessment() {
    }

    public RiskAssessment(Builder builder) {
        this.complianceRiskDetected = builder.complianceRiskDetected;
        this.securityRiskDetected = builder.securityRiskDetected;
    }
    public Boolean getComplianceRiskDetected() {
        return complianceRiskDetected;
    }

    public void setComplianceRiskDetected(Boolean complianceRiskDetected) {
        this.complianceRiskDetected = complianceRiskDetected;
    }
    public Boolean getSecurityRiskDetected() {
        return securityRiskDetected;
    }

    public void setSecurityRiskDetected(Boolean securityRiskDetected) {
        this.securityRiskDetected = securityRiskDetected;
    }
    public static class Builder {
        private Boolean complianceRiskDetected;

        private Boolean securityRiskDetected;

        public Builder complianceRiskDetected(Boolean complianceRiskDetected) {
            this.complianceRiskDetected = complianceRiskDetected;
            return this;
        }

        public Builder securityRiskDetected(Boolean securityRiskDetected) {
            this.securityRiskDetected = securityRiskDetected;
            return this;
        }

        public RiskAssessment build() {
            return new RiskAssessment(this);
        }
    }
}

