/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class TfAsset {
    /**
     * The asset symbol
     */
    @JsonProperty("symbol")
    private String symbol;

    /**
     * The asset adjustment factor for Trade Finance
     */
    @JsonProperty("asset_adjustment")
    private String assetAdjustment;

    /**
     * The liability adjustment factor for Trade Finance
     */
    @JsonProperty("liability_adjustment")
    private String liabilityAdjustment;

    public TfAsset() {
    }

    public TfAsset(Builder builder) {
        this.symbol = builder.symbol;
        this.assetAdjustment = builder.assetAdjustment;
        this.liabilityAdjustment = builder.liabilityAdjustment;
    }
    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    public String getAssetAdjustment() {
        return assetAdjustment;
    }

    public void setAssetAdjustment(String assetAdjustment) {
        this.assetAdjustment = assetAdjustment;
    }
    public String getLiabilityAdjustment() {
        return liabilityAdjustment;
    }

    public void setLiabilityAdjustment(String liabilityAdjustment) {
        this.liabilityAdjustment = liabilityAdjustment;
    }
    public static class Builder {
        private String symbol;

        private String assetAdjustment;

        private String liabilityAdjustment;

        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        public Builder assetAdjustment(String assetAdjustment) {
            this.assetAdjustment = assetAdjustment;
            return this;
        }

        public Builder liabilityAdjustment(String liabilityAdjustment) {
            this.liabilityAdjustment = liabilityAdjustment;
            return this;
        }

        public TfAsset build() {
            return new TfAsset(this);
        }
    }
}

