/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.TravelRuleParty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class TravelRuleData {
    @JsonProperty("beneficiary")
    private TravelRuleParty beneficiary;

    @JsonProperty("originator")
    private TravelRuleParty originator;

    @JsonProperty("is_self")
    private Boolean isSelf;

    /**
     * True if Coinbase is being used as an intermediary for a customer transfer.
     */
    @JsonProperty("is_intermediary")
    private Boolean isIntermediary;

    @JsonProperty("opt_out_of_ownership_verification")
    private Boolean optOutOfOwnershipVerification;

    public TravelRuleData() {
    }

    public TravelRuleData(Builder builder) {
        this.beneficiary = builder.beneficiary;
        this.originator = builder.originator;
        this.isSelf = builder.isSelf;
        this.isIntermediary = builder.isIntermediary;
        this.optOutOfOwnershipVerification = builder.optOutOfOwnershipVerification;
    }
    public TravelRuleParty getBeneficiary() {
        return beneficiary;
    }

    public void setBeneficiary(TravelRuleParty beneficiary) {
        this.beneficiary = beneficiary;
    }
    public TravelRuleParty getOriginator() {
        return originator;
    }

    public void setOriginator(TravelRuleParty originator) {
        this.originator = originator;
    }
    public Boolean getIsSelf() {
        return isSelf;
    }

    public void setIsSelf(Boolean isSelf) {
        this.isSelf = isSelf;
    }
    public Boolean getIsIntermediary() {
        return isIntermediary;
    }

    public void setIsIntermediary(Boolean isIntermediary) {
        this.isIntermediary = isIntermediary;
    }
    public Boolean getOptOutOfOwnershipVerification() {
        return optOutOfOwnershipVerification;
    }

    public void setOptOutOfOwnershipVerification(Boolean optOutOfOwnershipVerification) {
        this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
    }
    public static class Builder {
        private TravelRuleParty beneficiary;

        private TravelRuleParty originator;

        private Boolean isSelf;

        private Boolean isIntermediary;

        private Boolean optOutOfOwnershipVerification;

        public Builder beneficiary(TravelRuleParty beneficiary) {
            this.beneficiary = beneficiary;
            return this;
        }

        public Builder originator(TravelRuleParty originator) {
            this.originator = originator;
            return this;
        }

        public Builder isSelf(Boolean isSelf) {
            this.isSelf = isSelf;
            return this;
        }

        public Builder isIntermediary(Boolean isIntermediary) {
            this.isIntermediary = isIntermediary;
            return this;
        }

        public Builder optOutOfOwnershipVerification(Boolean optOutOfOwnershipVerification) {
            this.optOutOfOwnershipVerification = optOutOfOwnershipVerification;
            return this;
        }

        public TravelRuleData build() {
            return new TravelRuleData(this);
        }
    }
}

