/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.DateOfBirth;
import com.coinbase.prime.model.DetailedAddress;
import com.coinbase.prime.model.NaturalPersonName;
import com.coinbase.prime.model.enums.TravelRuleWalletType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class TravelRuleParty {
    @JsonProperty("name")
    private String name;

    @JsonProperty("detailed_address")
    private DetailedAddress detailedAddress;

    @JsonProperty("natural_person_name")
    private NaturalPersonName naturalPersonName;

    @JsonProperty("date_of_birth")
    private DateOfBirth dateOfBirth;

    @JsonProperty("telephone_number")
    private String telephoneNumber;

    @JsonProperty("wallet_type")
    private TravelRuleWalletType walletType;

    @JsonProperty("vasp_id")
    private String vaspId;

    @JsonProperty("vasp_name")
    private String vaspName;

    public TravelRuleParty() {
    }

    public TravelRuleParty(Builder builder) {
        this.name = builder.name;
        this.detailedAddress = builder.detailedAddress;
        this.naturalPersonName = builder.naturalPersonName;
        this.dateOfBirth = builder.dateOfBirth;
        this.telephoneNumber = builder.telephoneNumber;
        this.walletType = builder.walletType;
        this.vaspId = builder.vaspId;
        this.vaspName = builder.vaspName;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public DetailedAddress getDetailedAddress() {
        return detailedAddress;
    }

    public void setDetailedAddress(DetailedAddress detailedAddress) {
        this.detailedAddress = detailedAddress;
    }
    public NaturalPersonName getNaturalPersonName() {
        return naturalPersonName;
    }

    public void setNaturalPersonName(NaturalPersonName naturalPersonName) {
        this.naturalPersonName = naturalPersonName;
    }
    public DateOfBirth getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(DateOfBirth dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber;
    }
    public TravelRuleWalletType getWalletType() {
        return walletType;
    }

    public void setWalletType(TravelRuleWalletType walletType) {
        this.walletType = walletType;
    }
    public String getVaspId() {
        return vaspId;
    }

    public void setVaspId(String vaspId) {
        this.vaspId = vaspId;
    }
    public String getVaspName() {
        return vaspName;
    }

    public void setVaspName(String vaspName) {
        this.vaspName = vaspName;
    }
    public static class Builder {
        private String name;

        private DetailedAddress detailedAddress;

        private NaturalPersonName naturalPersonName;

        private DateOfBirth dateOfBirth;

        private String telephoneNumber;

        private TravelRuleWalletType walletType;

        private String vaspId;

        private String vaspName;

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder detailedAddress(DetailedAddress detailedAddress) {
            this.detailedAddress = detailedAddress;
            return this;
        }

        public Builder naturalPersonName(NaturalPersonName naturalPersonName) {
            this.naturalPersonName = naturalPersonName;
            return this;
        }

        public Builder dateOfBirth(DateOfBirth dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        public Builder telephoneNumber(String telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
            return this;
        }

        public Builder walletType(TravelRuleWalletType walletType) {
            this.walletType = walletType;
            return this;
        }

        public Builder vaspId(String vaspId) {
            this.vaspId = vaspId;
            return this;
        }

        public Builder vaspName(String vaspName) {
            this.vaspName = vaspName;
            return this;
        }

        public TravelRuleParty build() {
            return new TravelRuleParty(this);
        }
    }
}

