/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.BlockchainAddress;
import com.coinbase.prime.model.enums.TravelRuleWalletType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class TravelRuleWalletDetails {
    private TravelRuleWalletType walletType;

    private BlockchainAddress walletAddress;

    public TravelRuleWalletDetails() {
    }

    public TravelRuleWalletDetails(Builder builder) {
        this.walletType = builder.walletType;
        this.walletAddress = builder.walletAddress;
    }
    public TravelRuleWalletType getWalletType() {
        return walletType;
    }

    public void setWalletType(TravelRuleWalletType walletType) {
        this.walletType = walletType;
    }
    public BlockchainAddress getWalletAddress() {
        return walletAddress;
    }

    public void setWalletAddress(BlockchainAddress walletAddress) {
        this.walletAddress = walletAddress;
    }
    public static class Builder {
        private TravelRuleWalletType walletType;

        private BlockchainAddress walletAddress;

        public Builder walletType(TravelRuleWalletType walletType) {
            this.walletType = walletType;
            return this;
        }

        public Builder walletAddress(BlockchainAddress walletAddress) {
            this.walletAddress = walletAddress;
            return this;
        }

        public TravelRuleWalletDetails build() {
            return new TravelRuleWalletDetails(this);
        }
    }
}

