/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class ValidatorUnstakePreview {
    /**
     * Public address of the validator being unstaked from
     */
    @JsonProperty("validator_address")
    private String validatorAddress;

    /**
     * Estimated amount that would be unstaked from this validator (in ETH)
     */
    @JsonProperty("estimated_unstaking_amount")
    private String estimatedUnstakingAmount;

    /**
     * Estimated time until this validator&#39;s unstake completes, in hours
     */
    @JsonProperty("unstake_time_estimate_in_hours")
    private Double unstakeTimeEstimateInHours;

    /**
     * Estimated date when this validator&#39;s unstake will complete (ISO 8601)
     */
    @JsonProperty("estimated_unstake_date")
    private String estimatedUnstakeDate;

    public ValidatorUnstakePreview() {
    }

    public ValidatorUnstakePreview(Builder builder) {
        this.validatorAddress = builder.validatorAddress;
        this.estimatedUnstakingAmount = builder.estimatedUnstakingAmount;
        this.unstakeTimeEstimateInHours = builder.unstakeTimeEstimateInHours;
        this.estimatedUnstakeDate = builder.estimatedUnstakeDate;
    }
    public String getValidatorAddress() {
        return validatorAddress;
    }

    public void setValidatorAddress(String validatorAddress) {
        this.validatorAddress = validatorAddress;
    }
    public String getEstimatedUnstakingAmount() {
        return estimatedUnstakingAmount;
    }

    public void setEstimatedUnstakingAmount(String estimatedUnstakingAmount) {
        this.estimatedUnstakingAmount = estimatedUnstakingAmount;
    }
    public Double getUnstakeTimeEstimateInHours() {
        return unstakeTimeEstimateInHours;
    }

    public void setUnstakeTimeEstimateInHours(Double unstakeTimeEstimateInHours) {
        this.unstakeTimeEstimateInHours = unstakeTimeEstimateInHours;
    }
    public String getEstimatedUnstakeDate() {
        return estimatedUnstakeDate;
    }

    public void setEstimatedUnstakeDate(String estimatedUnstakeDate) {
        this.estimatedUnstakeDate = estimatedUnstakeDate;
    }
    public static class Builder {
        private String validatorAddress;

        private String estimatedUnstakingAmount;

        private Double unstakeTimeEstimateInHours;

        private String estimatedUnstakeDate;

        public Builder validatorAddress(String validatorAddress) {
            this.validatorAddress = validatorAddress;
            return this;
        }

        public Builder estimatedUnstakingAmount(String estimatedUnstakingAmount) {
            this.estimatedUnstakingAmount = estimatedUnstakingAmount;
            return this;
        }

        public Builder unstakeTimeEstimateInHours(Double unstakeTimeEstimateInHours) {
            this.unstakeTimeEstimateInHours = unstakeTimeEstimateInHours;
            return this;
        }

        public Builder estimatedUnstakeDate(String estimatedUnstakeDate) {
            this.estimatedUnstakeDate = estimatedUnstakeDate;
            return this;
        }

        public ValidatorUnstakePreview build() {
            return new ValidatorUnstakePreview(this);
        }
    }
}

