/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.coinbase.prime.model.UnstakingStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ValidatorUnstakingInfo {
    /**
     * The validator address (public key)
     */
    @JsonProperty("validator_address")
    private String validatorAddress;

    /**
     * List of active unstaking requests for this validator
     */
    @JsonProperty("statuses")
    private List<UnstakingStatus> statuses;

    public ValidatorUnstakingInfo() {
    }

    public ValidatorUnstakingInfo(Builder builder) {
        this.validatorAddress = builder.validatorAddress;
        this.statuses = builder.statuses;
    }
    public String getValidatorAddress() {
        return validatorAddress;
    }

    public void setValidatorAddress(String validatorAddress) {
        this.validatorAddress = validatorAddress;
    }
    public List<UnstakingStatus> getStatuses() {
        return statuses;
    }

    public void setStatuses(List<UnstakingStatus> statuses) {
        this.statuses = statuses;
    }
    public static class Builder {
        private String validatorAddress;

        private List<UnstakingStatus> statuses;

        public Builder validatorAddress(String validatorAddress) {
            this.validatorAddress = validatorAddress;
            return this;
        }

        public Builder statuses(List<UnstakingStatus> statuses) {
            this.statuses = statuses;
            return this;
        }

        public ValidatorUnstakingInfo build() {
            return new ValidatorUnstakingInfo(this);
        }
    }
}

