/*
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

package com.coinbase.prime.model;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;

public class Vasp {
    @JsonProperty("id")
    private String id;

    @JsonProperty("country_code")
    private String countryCode;

    @JsonProperty("lei_number")
    private String leiNumber;

    public Vasp() {
    }

    public Vasp(Builder builder) {
        this.id = builder.id;
        this.countryCode = builder.countryCode;
        this.leiNumber = builder.leiNumber;
    }
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getLeiNumber() {
        return leiNumber;
    }

    public void setLeiNumber(String leiNumber) {
        this.leiNumber = leiNumber;
    }
    public static class Builder {
        private String id;

        private String countryCode;

        private String leiNumber;

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public Builder countryCode(String countryCode) {
            this.countryCode = countryCode;
            return this;
        }

        public Builder leiNumber(String leiNumber) {
            this.leiNumber = leiNumber;
            return this;
        }

        public Vasp build() {
            return new Vasp(this);
        }
    }
}

