package com.coinbase.prime.model.activities;

public enum ActivityType {
    OTHER("OTHER_ACTIVITY_TYPE"),
    LIMIT_ORDER("ACTIVITY_TYPE_LIMIT_ORDER"),
    STOP_LIMIT_ORDER("ACTIVITY_TYPE_STOP_LIMIT_ORDER"),
    MARKET_ORDER("ACTIVITY_TYPE_MARKET_ORDER"),
    TWAP_ORDER("ACTIVITY_TYPE_TWAP_ORDER"),
    DEPOSIT("ACTIVITY_TYPE_DEPOSIT"),
    WITHDRAWAL("ACTIVITY_TYPE_WITHDRAWAL"),
    INTERNAL_TRANSFER("ACTIVITY_TYPE_INTERNAL_TRANSFER"),
    CREATE_WALLET("ACTIVITY_TYPE_CREATE_WALLET"),
    REMOVE_WALLET("ACTIVITY_TYPE_REMOVE_WALLET"),
    UPDATE_WALLET("ACTIVITY_TYPE_UPDATE_WALLET"),
    CAST_VOTE("ACTIVITY_TYPE_CAST_VOTE"),
    ENABLE_VOTING("ACTIVITY_TYPE_ENABLE_VOTING"),
    STAKE("ACTIVITY_TYPE_STAKE"),
    UNSTAKE("ACTIVITY_TYPE_UNSTAKE"),
    CHANGE_VALIDATOR("ACTIVITY_TYPE_CHANGE_VALIDATOR"),
    RESTAKE("ACTIVITY_TYPE_RESTAKE"),
    ADDRESS_BOOK("ACTIVITY_TYPE_ADDRESS_BOOK"),
    TEAM_MEMBERS("ACTIVITY_TYPE_TEAM_MEMBERS"),
    BILLING("ACTIVITY_TYPE_BILLING"),
    SECURITY("ACTIVITY_TYPE_SECURITY"),
    API("ACTIVITY_TYPE_API"),
    SETTINGS("ACTIVITY_TYPE_SETTINGS"),
    SMART_CONTRACT("ACTIVITY_TYPE_SMART_CONTRACT"),
    ALLOCATION_IN("ACTIVITY_TYPE_ALLOCATION_IN"),
    ALLOCATION_OUT("ACTIVITY_TYPE_ALLOCATION_OUT"),
    IN_REVERSAL("ACTIVITY_TYPE_IN_REVERSAL"),
    OUT_REVERSAL("ACTIVITY_TYPE_OUT_REVERSAL"),
    CONVERSION("ACTIVITY_TYPE_CONVERSION"),
    BLOCK_TRADE("ACTIVITY_TYPE_BLOCK_TRADE"),
    VWAP_ORDER("ACTIVITY_TYPE_VWAP_ORDER"),
    WEB3_MESSAGE("ACTIVITY_TYPE_WEB3_MESSAGE"),
    WEB3_TRANSACTION("ACTIVITY_TYPE_WEB3_TRANSACTION"),
    WEB3_DEVICE_RECOVERY("ACTIVITY_TYPE_WEB3_DEVICE_RECOVERY"),
    WEB3_RECREATE_BACKUP("ACTIVITY_TYPE_WEB3_RECREATE_BACKUP"),
    WEB3_ONBOARDING("ACTIVITY_TYPE_WEB3_ONBOARDING");

    private final String value;

    ActivityType(String value) {
        this.value = value;
    }

    public String toString() {
        return this.value;
    }
}
