package com.coinbase.prime.model.enums;


public enum ActivityCategory {
  OTHER_ACTIVITY_CATEGORY,
  ACTIVITY_CATEGORY_ORDER,
  ACTIVITY_CATEGORY_TRANSACTION,
  ACTIVITY_CATEGORY_ACCOUNT,
  ACTIVITY_CATEGORY_ALLOCATION,
  ACTIVITY_CATEGORY_LENDING
}

