package com.coinbase.prime.model.enums;


public enum ActivityStatus {
  OTHER_ACTIVITY_STATUS,
  ACTIVITY_STATUS_CANCELLED,
  ACTIVITY_STATUS_PROCESSING,
  ACTIVITY_STATUS_COMPLETED,
  ACTIVITY_STATUS_EXPIRED,
  ACTIVITY_STATUS_REJECTED,
  ACTIVITY_STATUS_FAILED
}

