package com.coinbase.prime.model.enums;


public enum CustodyActivityType {
  ACTIVITY_TYPE_GOVERNANCE_VOTE,
  ACTIVITY_TYPE_INVITATION,
  ACTIVITY_TYPE_WALLET_CHANGE,
  ACTIVITY_TYPE_API_KEY_CHANGE,
  ACTIVITY_TYPE_SETTINGS_CHANGE,
  ACTIVITY_TYPE_BILLING_PREFERENCE_CHANGE,
  ACTIVITY_TYPE_PAYMENT_METHOD_CHANGE,
  ACTIVITY_TYPE_WITHDRAWAL,
  ACTIVITY_TYPE_DEPOSIT,
  ACTIVITY_TYPE_CREATE_WALLET,
  ACTIVITY_TYPE_REMOVE_WALLET,
  ACTIVITY_TYPE_UPDATE_WALLET,
  ACTIVITY_TYPE_CAST_VOTE,
  ACTIVITY_TYPE_ENABLE_VOTING,
  ACTIVITY_TYPE_STAKE,
  ACTIVITY_TYPE_UNSTAKE,
  ACTIVITY_TYPE_CHANGE_VALIDATOR,
  ACTIVITY_TYPE_RESTAKE,
  ACTIVITY_TYPE_ADDRESS_BOOK,
  ACTIVITY_TYPE_TEAM_MEMBERS,
  ACTIVITY_TYPE_BILLING,
  ACTIVITY_TYPE_SECURITY,
  ACTIVITY_TYPE_API,
  ACTIVITY_TYPE_SETTINGS,
  ACTIVITY_TYPE_SMART_CONTRACT,
  ACTIVITY_TYPE_USER_CHANGE_REQUEST_NO_PAS,
  ACTIVITY_TYPE_WEB3_TRANSACTION,
  ACTIVITY_TYPE_WEB3_MESSAGE,
  ACTIVITY_TYPE_CLAIM_REWARDS
}

