package com.coinbase.prime.model.enums;


public enum FcmFuturesSweepStatus {
  FCM_FUTURES_SWEEP_STATUS_UNSPECIFIED,
  FCM_FUTURES_SWEEP_STATUS_PENDING,
  FCM_FUTURES_SWEEP_STATUS_CLOSED,
  FCM_FUTURES_SWEEP_STATUS_CANCELED,
  FCM_FUTURES_SWEEP_STATUS_PROCESSING
}

