package com.coinbase.prime.model.enums;


public enum FcmMarginCallState {
  FCM_MARGIN_CALL_STATE_UNSPECIFIED,
  FCM_MARGIN_CALL_STATE_CLOSED,
  FCM_MARGIN_CALL_STATE_ROLLED_OVER,
  FCM_MARGIN_CALL_STATE_DEFAULT,
  FCM_MARGIN_CALL_STATE_OFFICIAL
}

