package com.coinbase.prime.model.enums;


public enum InvoiceState {
  INVOICE_STATE_UNSPECIFIED,
  INVOICE_STATE_IMPORTED,
  INVOICE_STATE_BILLED,
  INVOICE_STATE_PARTIALLY_PAID,
  INVOICE_STATE_PAID
}

