package com.coinbase.prime.model.enums;


public enum LoanType {
  LOAN_TYPE_UNSET,
  BILATERAL_LENDING,
  TRADE_FINANCE,
  PORTFOLIO_MARGIN,
  SHORT_COLLATERAL_LOAN,
  SHORT_COLLATERAL,
  CROSS_MARGIN
}

