package com.coinbase.prime.model.enums;


public enum TransactionStatus {
  TRANSACTION_CREATED,
  TRANSACTION_REQUESTED,
  TRANSACTION_APPROVED,
  TRANSACTION_GASSING,
  TRANSACTION_GASSED,
  TRANSACTION_PROVISIONED,
  TRANSACTION_PLANNED,
  TRANSACTION_PROCESSING,
  TRANSACTION_RESTORED,
  TRANSACTION_DONE,
  TRANSACTION_IMPORT_PENDING,
  TRANSACTION_IMPORTED,
  TRANSACTION_CANCELLED,
  TRANSACTION_REJECTED,
  TRANSACTION_DELAYED,
  TRANSACTION_RETRIED,
  TRANSACTION_FAILED,
  TRANSACTION_EXPIRED,
  TRANSACTION_BROADCASTING,
  OTHER_TRANSACTION_STATUS,
  TRANSACTION_CONSTRUCTED
}

