package com.coinbase.prime.model.enums;


public enum ValidatorStatus {
  VALIDATOR_STATUS_UNSPECIFIED,
  VALIDATOR_STATUS_PENDING,
  VALIDATOR_STATUS_ACTIVE,
  VALIDATOR_STATUS_EXITING,
  VALIDATOR_STATUS_EXITED,
  VALIDATOR_STATUS_WITHDRAWN
}

