package com.coinbase.prime.model.enums;


public enum XMMarginLevel {
  XM_MARGIN_LEVEL_UNSPECIFIED,
  HEALTHY_THRESHOLD,
  DEFICIT_THRESHOLD,
  WARNING_THRESHOLD,
  URGENT_MARGIN_CALL_THRESHOLD,
  LIQUIDATION_THRESHOLD
}

