package com.coinbase.prime.model.allocations;

public enum AllocationStatus {
    ALLOCATION_STATUS_UNSPECIFIED,
    ALLOCATION_STATUS_ALLOCATION_PENDING,
    ALLOCATION_STATUS_ALLOCATION_ACCEPTED,
    ALLOCATION_STATUS_ALLOCATION_REJECTED,
    ALLOCATION_STATUS_ALLOCATION_ALLOCATED
}
