/*
 * Copyright 2024-present Coinbase Global, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package com.coinbase.prime.orders;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Response object for accepting a quote and creating an order.
 * 
 * Accepts the quote received by the quote request and creates an order with the provided quote ID.
 * Always required: portfolio_id, product_id, side, quote_id, client_quote_id.
 */
public class AcceptQuoteResponse {
  /** The order ID generated by Coinbase */
  @JsonProperty("order_id")
  private String orderId;

  public AcceptQuoteResponse() {
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }
}
