package com.coinbase.prime.model.invoice;

public enum InvoiceType {
    INVOICE_TYPE_UNSPECIFIED,
    INVOICE_TYPE_AUC_FEE,
    INVOICE_TYPE_MINIMUM_FEE,
    INVOICE_TYPE_WITHDRAWAL_FEE,
    INVOICE_TYPE_NEW_WALLET_FEE,
    INVOICE_TYPE_STAKING_FEE
}
