name: Daily Model Generation

on:
  schedule:
    # Run at 1 AM UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          architecture: x64

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate models from OpenAPI spec
        run: mvn -Pgenerate-models

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update generated models from OpenAPI spec'
          branch: automated/model-generation-${{ github.run_number }}
          delete-branch: true
          title: 'chore: Update generated models from OpenAPI spec'
          body: |
            ## Automated Model Generation
            
            This PR contains automatically generated updates to the SDK models based on the latest OpenAPI specification from `https://api.prime.coinbase.com/v1/openapi.yaml`.
            
            ### What changed?
            - Models generated/updated via `mvn -Pgenerate-models`
            - Changes reflect updates to the Prime API specification
            
            ### How to review
            1. Verify that generated files follow SDK conventions
            2. Check that new models have proper Builder patterns and license headers
            3. Ensure enums are properly generated
            4. Run tests to verify compatibility: `mvn clean install`
            
            ### Generated by
            Workflow: `${{ github.workflow }}`
            Run: `${{ github.run_id }}`
            Triggered: `${{ github.event_name }}`
          labels: |
            automated
            model-generation
          assignees: ${{ github.repository_owner }}

      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: echo "No model changes detected. Skipping PR creation."
